feat: 自定义字段新增 cascading 类型
teambition/teambition-sdk pull request #675
Opened 2019-10-08 09:18 UTC by 2eha0

2019-10-09 09:12 UTC, aicest approved these changes

2019-10-09 09:25 UTC, 2eha0 commented
@aicest 测试版本: v0.12.69-alpha.3-cascading

2019-10-11 09:40 UTC, aicest commented
@2eha0 还得给 custom-field-schema 补充 mustSelectLeaf 字段。

2019-10-16 11:52 UTC, aicest commented
@2eha0 v0.12.69-alpha.6-cascading

2019-10-23 03:15 UTC, aicest requested changes

2019-10-23 03:15 UTC, aicest commented on src/schemas/CustomFieldEntity.ts
> +  payload?: CustomFieldCascadingPayloadSchema
这里是为了服务录入（POST/PUT）时向后端传值对吧，我觉得可以拿掉 Schema 后辍。

2019-10-23 03:15 UTC, aicest commented on src/schemas/CustomFieldLink.ts
> +  payload?: CustomFieldCascadingPayloadSchema
后端实际不会返回这个字段，只会在录入（POST/PUT）时要求传给后端。

payload 数据是通过一个单独接口返回的。

2019-10-23 04:00 UTC, aicest approved these changes

2019-11-20 07:36 UTC, merged